spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/discord?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: sqli4abella@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialects
  data:
    redis:
      host: localhost
      port: 6379
logging:
  file:
    path: ./logs
    max-size: 10MB
springdoc:
  swagger-ui:
    path: /api-docs
    operationSorter: method
    tagsSorter: alpha
    syntaxHighlight:
      theme: arta
